# Generated by Django 2.1 on 2018-10-19 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20181019_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StockName', models.CharField(blank=True, max_length=100)),
                ('CurrentPrice', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='userstockdisplay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StockName', models.CharField(max_length=100)),
                ('NumberOfStock', models.IntegerField()),
                ('SellingPrice', models.FloatField()),
            ],
        ),
    ]
