# Generated by Django 2.1 on 2018-10-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_stock_userstockdisplay'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('StockNews', models.TextField(blank=True)),
            ],
        ),
    ]
