# Generated by Django 2.1 on 2018-10-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstockdisplay',
            name='TeamId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
