# Generated by Django 2.1 on 2018-10-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_userstockdisplay_teamid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstockdisplay',
            name='TeamId',
            field=models.IntegerField(),
        ),
    ]
