# Generated by Django 2.1 on 2018-10-19 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_userform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserForm',
        ),
    ]
