# Generated by Django 2.1 on 2018-10-23 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0039_auto_20181023_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstockdisplay',
            name='StockName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Stock'),
        ),
        migrations.AlterField(
            model_name='userstockdisplay',
            name='TeamId',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
